# Generated by Django 2.0.2 on 2019-03-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_manga_manga_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='Date de sortie du tome')),
                ('book_name', models.CharField(max_length=200, verbose_name='Nom du tome')),
                ('book_resum', models.CharField(max_length=1500, verbose_name='Un petit résumé du tome')),
                ('book_cover', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_name',
            field=models.CharField(max_length=200, verbose_name='Nom de la série'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_number',
            field=models.IntegerField(default=1, verbose_name='Nombre de tome'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pub_date',
            field=models.DateField(verbose_name='Date de sortie de série'),
        ),
        migrations.AddField(
            model_name='book',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.Manga'),
        ),
    ]
