# Generated by Django 2.0.2 on 2019-03-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_auto_20190326_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
    ]
