# Generated by Django 2.0.2 on 2019-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_auto_20190407_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom du tome'),
        ),
    ]
