# Generated by Django 2.0.2 on 2019-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/images'),
        ),
    ]
