# Generated by Django 2.0.2 on 2020-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0008_auto_20190407_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom de fichier de la couverture'),
        ),
    ]
