# Generated by Django 2.0.2 on 2020-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0009_book_book_cover_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_end',
            field=models.CharField(choices=[('KO', 'En cours'), ('OK', 'Terminé')], default='KO', max_length=2),
        ),
    ]
