# Generated by Django 2.0.2 on 2020-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0011_remove_manga_manga_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_end',
            field=models.CharField(choices=[('KO', 'En cours'), ('OK', 'Terminé')], default='KO', max_length=2, verbose_name='Statut de la série'),
        ),
    ]
