# Generated by Django 2.0.2 on 2020-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0013_auto_20200521_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom du tome'),
        ),
    ]
