# Generated by Django 2.0.2 on 2020-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0014_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Nom de fichier de la couverture'),
        ),
    ]
