# Generated by Django 2.0.2 on 2020-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0015_auto_20200521_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_cover_name',
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_cover',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/images'),
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_cover_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Nom de fichier de la couverture'),
        ),
    ]
