# Generated by Django 3.1.3 on 2020-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0017_auto_20201109_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_cover',
            field=models.FileField(blank=True, null=True, upload_to='mangas/static/mangas'),
        ),
    ]
